name: github-python-actions
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: installing requirements
        uses: py-actions/py-dependency-install@v2      
        with:
          path: "./requirements.txt"
      - name: linking with heroku
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: knire-ci-me-dice-on-demand
          heroku_email: "daniel.naranjo1999@gmail.com"
      - name: unit test
        run: |
          python3 -m venv venv
          venv/bin/activate
          python3 -m pytest -v tests/test_dice.py
          flask run
  
  

